version: '3.7'

services:
  iva:
    build:
      context: .
    command: watchmedo auto-restart -p "*.py" -R python3 -- main.py
    volumes:
      - .:/usr/src/app/
    ports:
      - "5678:5678"
      - "5000:5000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:iva.docker.localhost
      - traefik.docker.network=iva_network
    networks:
      - iva_network

networks:
  iva_network:
    name: iva_network